name: Python CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # replace with the version of Python you need

    - name: Install requests module
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Display installed packages
      run: |
        python -m pip freeze

    - name: Run main.py
      run: python main.py
