name: Push to Release

on:
  push:
    branches:
      - main

jobs:
  push_to_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PowerShell
        uses: actions/setup-powershell@v2
        with:
          pwsh-version: '7.x'  # Specify the desired PowerShell version

      - name: Run PowerShell script
        run: |
          $ErrorActionPreference = 'Stop'
          .push-to-release.ps1
