name: Push to Release

on:
  push:
    branches:
      - main

jobs:
  push_to_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if hello.py exists
        run: |
          if [ -f hello.py ]; then
            echo "File hello.py exists."
          else
            echo "Error: hello.py does not exist."
            exit 1
          fi

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Checkout release branch
        run: git checkout -b release

      - name: Merge changes from main
        run: git merge main

      - name: Push changes to release
        run: git push origin release

      - name: Create pull request
        run: |
          TITLE="Merge main into release"
          BODY="Automated PR from GitHub Actions"
          SOURCE_BRANCH="main"
          TARGET_BRANCH="release"
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -d "{\"title\":\"$TITLE\",\"body\":\"$BODY\",\"head\":\"$SOURCE_BRANCH\",\"base\":\"$TARGET_BRANCH\"}" -H "Content-Type: application/json" "https://api.github.com/repos/${{ github.repository }}/pulls"

      - name: Switch back to main
        run: git checkout main

      - name: Complete
        run: echo "Changes successfully pushed to release."
