name: Push to Release

on:
  push:
    branches:
      - main

jobs:
  push_to_release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "Anilathmacloudeqs"
        git config user.email "anilathma@cloudeqs.com"

    - name: Check File Existence
      run: |
        fileToCheck="hello.py"
        if [ -e $fileToCheck ]; then
          echo "File Existence Check Result: $(cat $fileToCheck)"
        else
          echo "File $fileToCheck not found."
          exit 1
        fi

    - name: Create or Checkout Release Branch
      run: |
        destinationBranch="release"
        git checkout $destinationBranch 2>/dev/null || git checkout -b $destinationBranch

    - name: Merge Changes from Main
      run: git merge main

    - name: Push Changes to Release
      run: git push origin $destinationBranch

    - name: Switch Back to Main
      run: git checkout main
