name: Push to Release

on:
  push:
    branches:
      - main

jobs:
  push_to_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PowerShell
        uses: PowerShell/setup-powershell@v0.0.10

      - name: Run PowerShell script
        run: |
          $ErrorActionPreference = 'Stop'
          .\path\to\your\script.ps1
